#!/bin/bash

javaJreFlag=1
osUpdateFlag=1
rustFlag=1
rustProgramsFlag=1
xWindowsFlag=1
symlinksFlag=1
pipPackagesFlag=1
myReposFlag=1

# -------------------------------------------------------------------------- }}}
# {{{ Other variables used during product installation.

cloneRoot=$HOME/git

# -------------------------------------------------------------------------- }}}