#!/bin/bash
# -------------------------------------------------------------------------- }}}
# {{{ Products to install.

gitBashPromptFlag=1
luarocksPackages=1
lunarVimFlag=1
myReposFlag=1
neovimBuildFlag=1
neovimPluginsFlag=1
osUpdateFlag=0
osUpdateKeysFlag=0
otherAppsFlag=1
pacmanPackagesFlag=1
pipPackagesFlag=1
symlinksFlag=1
texPackagesFlag=1
vimPluginsFlag=1
yayPackagesFlag=1
rbenvFlag=1
rustFlag=1

# -------------------------------------------------------------------------- }}}
# {{{ Other variables used during product installation.

# The root personal repositories are cloned to.
cloneRoot=$HOME/git

# -------------------------------------------------------------------------- }}}